server:
  port: 8888
spring:
  profiles:
    active: '@spring.profiles.active@' #此处由maven的环境选择决

self:
  shareFolder: "file:E:\\迅雷下载\\ShareFolder\\"
  enable: true

#nacos:
#  config:
#    server-addr: 127.0.0.1:8848
#    data-id: tool-config
#    type: yaml
#    auto-refresh: true
#    bootstrap:
#      enable: true
#      log:
#        enable: true



